[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "frontend"
path = "./src/main.rs"
bench = false


[dependencies]
core = { path = "../core" }
crossterm = "0.22.1"
nanorand = "0.6.1"
arrayvec = "0.7.2"
